### ISSUE TITLE
ft_atoi 함수의 효율성 문제

### ISSUE THREAD

**Issue by cos18** [skdlsco/factorization#3]
코드가 잘못 작동되었다는 이슈를 제외하고, 코드의 효율성 관련해 의문이 들어 이슈를 작성합니다.

현제 로직 상으론

1. input으로 들어온 문자열을 숫자로 변환
2. 문자열이 범위에 넘어서는지 확인

으로 되어있는데, 순서가 비효율적이라는 생각이 듭니다. 같은 문자열을 두번 확인하는 작업이 들어가네요. 가능하다면 위 두 순서를 바꾸거나, 변환된 숫자로 범위를 확인하는 과정으로 2번을 대체하는게 이 함수가 더 효율적으로 작동할 것 같습니다.

**Comment by skdlsco** [comment]
효율성에 관한 좋은 지적 감사드립니다.
하지만 말씀해주신 변환된 숫자로 범위를 확인하는 과정은 무리인 것 같습니다.
맨 앞이 0인부분을 미리 제거하는 방식과 숫자의 길이가 10이 넘는 경우 바로 while문을 멈추게 했었다면 좋았겠다는 생각이 저도 이제서야 드네요.
효율성에 관해서 깊게 생각하지 못한 부분을 짚어 주셔서 다시한번 감사드립니다.
